### PR TITLE
add channel: thanksforloitering

### PR DESCRIPTION
**Pull request by mbaralle**

### CODE REVIEW

**Review by stephanebruckert — APPROVED** [review]
thanksforyourpr  😃

**Comment by stephanebruckert** [comment]
Weirdly it wasn't added, maybe a bug, I'll have a look

**Comment by mbaralle** [comment]
This was merged into _patch-1_, could it be the cause?

**Comment by stephanebruckert** [comment]
I ran it manually and it worked:

https://open.spotify.com/playlist/1T8sD1I1DQYoO3ppXAVBXX?si=6d6f03f1190e4e15

**Pull request merged**
