### PR TITLE
[channel] Add Sinchi Collective

### PR DESCRIPTION
**Pull request by SinchiCollective**
H

### CODE REVIEW

**Comment by stephanebruckert** [comment]
Hi @SinchiCollective, do you own this channel?

I would love to merge this but it currently wouldn't work very well for technical reasons.

### Problem

Most track titles in the channel are followed by the label name, such as: `Artist – Track (label name)`. The problem is, it is impossible to automatically detect whether `(label name)` is part of the track name or not. For example: 
 - [`Della - Traffic (BadWolf Remix)`](https://www.youtube.com/watch?v=O3LpvY9yFos) => this is a valid track name, when searching for that track on Spotify, we find the track
 - [`Jepe - Cutting Edge (Tenampa Recordings)`](https://www.youtube.com/watch?v=fPcdoUzvk1o) => this is not a valid track name due to the extra label information, when searching for `Jepe Cutting Edge Tenampa` the track is not found , whereas it would have been found searching for `Jepe Cutting Edge`. But also, even though we can detect what's in parens, we cannot safely remove that because we want to keep Remix information just like in the example above
 - [`Enzo Elia - Hinterhof Disco Dub (Amarcord Remix) (Buttress Records)`](https://www.youtube.com/watch?v=GstPKIlagPE) => this is not a valid track name either, but we manage to detect that the second group of parens is unexpected as a track is usually not remixed twice. Therefore the Spotify track will be found because [we automatically remove extra groups of parens](https://github.com/mirrorfm/trackfilter/blob/8f9ea931ebee524bd03afa3f8727658c07c77733/tests/test_trackfilter.py#L76..L82).

### Solution

The solution is simple. All youtube tracks should be renamed to either:

 - remove the label information (could be moved to the upload description),
 - OR surround labels with square brackets `[]` instead of parentheses `()`. It will then be easy for us to [automatically remove the label info](https://github.com/mirrorfm/trackfilter/blob/8f9ea931ebee524bd03afa3f8727658c07c77733/tests/test_trackfilter.py#L24). For example:
     - `Della - Traffic (BadWolf Remix)` is already valid
     - `Jepe - Cutting Edge (Tenampa Recordings)` => `Jepe - Cutting Edge [Tenampa Recordings]`
     - `Enzo Elia - Hinterhof Disco Dub (Amarcord Remix) (Buttress Records)` => `Enzo Elia - Hinterhof Disco Dub (Amarcord Remix) [Buttress Records]`

Doing this will also help people who use [audioscrobblers on youtube](https://github.com/web-scrobbler/web-scrobbler), as they are currently scrobbling incorrect track metadata.

------------

I'm guessing updating up to 700 video titles is big toil, but it's definitely worth it

**Review by stephanebruckert — CHANGES_REQUESTED** [review]

**Comment by SinchiCollective** [comment]
Hi Stephane,

Thanks for the heads up, seems I have quite a job to do. Will write back when its done.

Cheers

Tom

From: Stéphane Bruckert ***@***.***>
Reply to: mirrorfm/data ***@***.***>
Date: Thursday, 13 May 2021 at 22:24
To: mirrorfm/data ***@***.***>
Cc: Tom Wheeler ***@***.***>, Mention ***@***.***>
Subject: Re: [mirrorfm/data] Update youtube-channels.csv (#11)


Hi @SinchiCollective<https://github.com/SinchiCollective>, do you own this channel?

I would love to merge this but it currently wouldn't work very well for technical reasons.

Problem

Most track titles in the channel are followed by the label name, such as: Artist – Track (label name). The problem is, it is impossible to automatically detect whether (label name) is part of the track name or not. For example:

  *   Della - Traffic (BadWolf Remix)<https://www.youtube.com/watch?v=O3LpvY9yFos> => this is a valid track name, when searching for that track on Spotify, we find the track
  *   Jepe - Cutting Edge (Tenampa Recordings)<https://www.youtube.com/watch?v=fPcdoUzvk1o> => this is not a valid track name due to the extra label information, when searching for Jepe Cutting Edge Tenampa the track is not found , whereas it would have been found searching for Jepe Cutting Edge. But also, even though we can detect what's in parens, we cannot safely remove that because we want to keep Remix information just like in the example above
  *   Enzo Elia - Hinterhof Disco Dub (Amarcord Remix) (Buttress Records)<https://www.youtube.com/watch?v=GstPKIlagPE> => this is not a valid track name either, but we manage to detect that the second group of parens is unexpected as a track is usually not remixed twice. Therefore the Spotify track will be found because we automatically remove extra groups of parens<https://github.com/mirrorfm/trackfilter/blob/8f9ea931ebee524bd03afa3f8727658c07c77733/tests/test_trackfilter.py#L76..L82>.

Solution

The solution is simple. All youtube tracks should be renamed to either:

  *   remove the label information (could be moved to the upload description),
  *   OR surround labels with square brackets [] instead of parentheses (). It will then be easy for us to automatically remove the label info<https://github.com/mirrorfm/trackfilter/blob/8f9ea931ebee524bd03afa3f8727658c07c77733/tests/test_trackfilter.py#L24>. For example:
     *   Della - Traffic (BadWolf Remix) is already valid
     *   Jepe - Cutting Edge (Tenampa Recordings) => Jepe - Cutting Edge [Tenampa Recordings]
     *   Enzo Elia - Hinterhof Disco Dub (Amarcord Remix) (Buttress Records) => Enzo Elia - Hinterhof Disco Dub (Amarcord Remix) [Buttress Records]

Doing this will also help people who use audioscrobblers on youtube<https://github.com/web-scrobbler/web-scrobbler>, as they are currently scrobbling incorrect track metadata.

________________________________

I'm guessing updating up to 700 video titles is big toil, but it's definitely worth it

**Comment by stephanebruckert** [comment]
Awesome @SinchiCollective, thanks! let me know when you are ready

**Comment by SinchiCollective** [comment]
So it done 😊 let me know if its now good to be set up?

Cheers

Tom

From: Stéphane Bruckert ***@***.***>
Reply to: mirrorfm/data ***@***.***>
Date: Saturday, 22 May 2021 at 14:31
To: mirrorfm/data ***@***.***>
Cc: Tom Wheeler ***@***.***>, Mention ***@***.***>
Subject: Re: [mirrorfm/data] [channel] Add Sinchi Collective (#11)


Awesome @SinchiCollective<https://github.com/SinchiCollective>, thanks! let me know when you are ready

**Comment by stephanebruckert** [comment]
Amazing, thanks! Here are your links:

https://open.spotify.com/playlist/7sd3nFrzl9itGooHqItGFG?si=be71b3cefc3f483e
https://mirror.fm/youtube/UCkJiiJt2HkHMSeZJIIQgQTA/sinchi-collective/

**Comment by SinchiCollective** [comment]
Hi Stephane,

One final question, how quickly do new tracks go up on the playlist? As we post every day but don’t see new ones added yet, is that once every week / month etc

Cheers

Tom

From: Stéphane Bruckert ***@***.***>
Reply to: mirrorfm/data ***@***.***>
Date: Monday, 24 May 2021 at 10:54
To: mirrorfm/data ***@***.***>
Cc: Tom Wheeler ***@***.***>, Mention ***@***.***>
Subject: Re: [mirrorfm/data] [channel] Add Sinchi Collective (#11)


Amazing, thanks! Here are your links:

https://open.spotify.com/playlist/7sd3nFrzl9itGooHqItGFG?si=be71b3cefc3f483e
https://mirror.fm/youtube/UCkJiiJt2HkHMSeZJIIQgQTA/sinchi-collective/

**Comment by stephanebruckert** [comment]
@SinchiCollective good point, it used to be very fast but as we get more and more channels it became slower.

I think it was taking about 5 days to revisit ~500 channels.

I've just increased the frequency at which it runs by 15, so it should now revisit all channels every 8 hours 👍

**Comment by SinchiCollective** [comment]
Great 😊

From: Stéphane Bruckert ***@***.***>
Reply to: mirrorfm/data ***@***.***>
Date: Thursday, 27 May 2021 at 02:05
To: mirrorfm/data ***@***.***>
Cc: Tom Wheeler ***@***.***>, Mention ***@***.***>
Subject: Re: [mirrorfm/data] [channel] Add Sinchi Collective (#11)


@SinchiCollective<https://github.com/SinchiCollective> good point, it used to be very fast but as we get more and more channels it became slower.

I think it was taking about 5 days to revisit ~500 channels.

I've just increased the frequency at which it runs by 15, so it should now revisit all channels every 8 hours 👍

**Pull request merged**
