### PR TITLE
Add Dream Chimney

### PR DESCRIPTION
**Pull request by jdhodges**

### CODE REVIEW

**Review by stephanebruckert — COMMENTED** [review]
Looks like we first need to update the trackfilter package to handle tracks that follow this pattern:

> Artist "Track" 

See https://github.com/mirrorfm/trackfilter/blob/master/tests/test_trackfilter.py

**Comment by jdhodges** [comment]
I thought it might be covered by https://github.com/mirrorfm/trackfilter/blob/master/tests/test_trackfilter.py#L59

I absolutely love this project by the way!

**Comment by stephanebruckert** [comment]
Oh nice catch, didn't remember about it! Merging then

Thanks, I'm happy you like it

**Comment by stephanebruckert** [comment]
https://open.spotify.com/playlist/40cwM5WURk3NrFPaXC9NJk?si=EHUHWutnQvC_oRXfAEGHLg

**Pull request merged**
